package com.ecodispatch.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * DistrictAlert — JPA Entity representing a monitored geographic climate zone.
 *
 * <p>Each record maps to one district sub-zone (e.g., Saidapet in Chennai).
 * The {@code status} field reflects the AI triage result, and
 * {@code aiActionPlan} stores the plain-language dispatch instruction
 * returned by the IBM Granite model agent.</p>
 *
 * Status lifecycle:
 *   NORMAL  →  ALERT_PENDING_WATERING  →  DISPATCHED
 */
@Entity
@Table(name = "district_alerts")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DistrictAlert {

    /** Primary key — auto-generated surrogate identifier. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The parent district name (state administrative division).
     * Examples: "Chennai", "Coimbatore", "Madurai"
     */
    @Column(nullable = false, length = 100)
    private String districtName;

    /**
     * The specific sub-zone or locality within the district.
     * Examples: "Saidapet", "Ukkadam", "Anna Nagar"
     */
    @Column(nullable = false, length = 100)
    private String zoneName;

    /**
     * Latest recorded land-surface temperature in degrees Celsius.
     * Threshold for CRITICAL_ANOMALY flag: > 40.0°C
     */
    @Column(nullable = false)
    private Double temperature;

    /**
     * Urban tree canopy coverage as a percentage of zone area (0.0 – 100.0).
     * Low values (< 15%) compound heat-island severity.
     */
    @Column(nullable = false)
    private Double canopyPercentage;

    /** Decimal latitude for Leaflet.js map marker placement. */
    @Column(nullable = false)
    private Double latitude;

    /** Decimal longitude for Leaflet.js map marker placement. */
    @Column(nullable = false)
    private Double longitude;

    /**
     * Triage / dispatch status of this zone record.
     *
     * <ul>
     *   <li>{@code NORMAL}                  — No anomaly detected.</li>
     *   <li>{@code ALERT_PENDING_WATERING}  — Anomaly confirmed; awaiting crew assignment.</li>
     *   <li>{@code DISPATCHED}              — Field crew has been dispatched and confirmed.</li>
     * </ul>
     */
    @Column(nullable = false, length = 50)
    private String status;

    /**
     * Full plain-language action plan generated by the IBM Granite model agent.
     * Stored as TEXT to handle responses up to several hundred tokens.
     * Example: "Deploy watering tanker immediately to Saidapet to alleviate
     * local soil moisture crisis. Initiate emergency native-tree planting
     * in 0.5 km radius to restore canopy cover."
     */
    @Column(columnDefinition = "TEXT")
    private String aiActionPlan;
}
